### ISSUE TITLE
Pix2Pix 3->1 channel

### ISSUE THREAD

**Issue by AN3Orik** [victorca25/traiNNer#79]
Hi!
Is it possible to initialize pix2pix for working with 3 channel input image and 1 channel output?

Trying with following options:

```
name: 001_pix2pix_test
use_tb_logger: true
model: pix2pix
scale: 1
gpu_ids: [0]
use_amp: true
use_swa: false

# Dataset options:
datasets:
  train:
    name: test
    mode: aligned
    outputs: AB
    dataroot_B: '../datasets/test/B'
    dataroot_A: '../datasets/test/A'
    
    use_shuffle: true
    n_workers: 8
    batch_size: 2
    virtual_batch_size: 2
    preprocess: none
    crop_size: 256 
    input_nc: 3
    output_nc: 1
    image_channels: 3

# Generator options:
network_G:
    strict: false
    which_model_G: unet_net

# Discriminator options:
network_D:
    strict: true
    which_model_D: patchgan
    in_nc: 4
```

And got this in few secs after training start:

```
2024-01-03 11:07:26.963466: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
24-01-03 11:07:34.462 - WARNING: From c:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.
24-01-03 11:07:35.310 - INFO: Random seed: 0
24-01-03 11:07:35.677 - INFO: Dataset [AlignedDataset - test] is created.
24-01-03 11:07:35.677 - INFO: Number of train images: 3,159, epoch iters: 1,579
24-01-03 11:07:35.678 - INFO: Total epochs needed: 32 for iters 50,000
24-01-03 11:07:35.910 - INFO: AMP library available
24-01-03 11:07:36.229 - INFO: Initialization method [kaiming]
24-01-03 11:07:36.900 - INFO: Initialization method [kaiming]
24-01-03 11:07:36.927 - INFO: GAN enabled
24-01-03 11:07:36.929 - INFO: AMP enabled
24-01-03 11:07:36.930 - INFO: Network G structure: DataParallel - UnetGenerator, with parameters: 54,413,955
24-01-03 11:07:36.930 - INFO: Network D structure: DataParallel - NLayerDiscriminator, with parameters: 2,766,657
24-01-03 11:07:36.931 - INFO: Model [Pix2PixModel] created.
24-01-03 11:07:36.930 - INFO: Network G structure: DataParallel - UnetGenerator, with parameters: 54,413,955
24-01-03 11:07:36.930 - INFO: Network D structure: DataParallel - NLayerDiscriminator, with parameters: 2,766,657
24-01-03 11:07:36.931 - INFO: Model [Pix2PixModel] created.
24-01-03 11:07:36.931 - INFO: Start training from epoch: 0, iter: 0
Traceback (most recent call last):
  File "f:\GIT\traiNNer\codes\train.py", line 500, in <module>
    main()
  File "f:\GIT\traiNNer\codes\train.py", line 496, in main
    fit(model, opt, dataloaders, steps_states, data_params, loggers)
  File "f:\GIT\traiNNer\codes\train.py", line 238, in fit
    model.optimize_parameters(virtual_step)  # calculate loss functions, get gradients, update network weights
  File "f:\GIT\traiNNer\codes\models\pix2pix_model.py", line 219, in optimize_parameters
    self.backward_D()
  File "f:\GIT\traiNNer\codes\models\pix2pix_model.py", line 146, in backward_D
    self.log_dict = self.backward_D_Basic(
  File "f:\GIT\traiNNer\codes\models\base_model.py", line 871, in backward_D_Basic
    l_d_total, gan_logs = self.adversarial(
  File "c:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "c:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "f:\GIT\traiNNer\codes\models\losses.py", line 595, in forward
    return self.conditional_discriminator(
  File "f:\GIT\traiNNer\codes\models\losses.py", line 530, in conditional_discriminator
    return self.regular_discriminator(
  File "f:\GIT\traiNNer\codes\models\losses.py", line 536, in regular_discriminator
    pred_d_fake, pred_d_real = self.get_predictions_dis(
  File "f:\GIT\traiNNer\codes\models\losses.py", line 475, in get_predictions_dis
    pred_d_fake = netD(fake.detach())
  File "c:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "c:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "c:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\parallel\data_parallel.py", line 183, in forward
    return self.module(*inputs[0], **module_kwargs[0])
  File "c:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "c:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "f:\GIT\traiNNer\codes\models\modules\architectures\discriminators.py", line 579, in forward
    return self.model(x)
  File "c:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "c:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "c:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\modules\container.py", line 215, in forward
    input = module(input)
  File "c:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "c:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "c:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\modules\conv.py", line 460, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "c:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\modules\conv.py", line 456, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Given groups=1, weight of size [64, 4, 4, 4], expected input[2, 6, 1024, 1024] to have 4 channels, but got 6 channels instead

```

I'm double checked: all A images got 3 channels and all B images got only 1 grayscale channel.
Whats going on and it's a possible at all?

**Comment by AN3Orik** [comment]
Seems broken. Switched to original pix2pix repository and all works perfectly.
