### ISSUE TITLE
AttributeError: module 'collections' has no attribute 'Iterable'

### ISSUE THREAD

**Issue by v0vanch0** [victorca25/traiNNer#80]
Traceback (most recent call last):
  File "D:\PycharmProjects\traiNNer\codes\train.py", line 500, in <module>
    main()
  File "D:\PycharmProjects\traiNNer\codes\train.py", line 496, in main
    fit(model, opt, dataloaders, steps_states, data_params, loggers)
  File "D:\PycharmProjects\traiNNer\codes\train.py", line 224, in fit
    for n, train_data in enumerate(dataloaders['train'], start=1):
  File "D:\venvs\AI\Lib\site-packages\torch\utils\data\dataloader.py", line 631, in __next__
    data = self._next_data()
           ^^^^^^^^^^^^^^^^^
  File "D:\venvs\AI\Lib\site-packages\torch\utils\data\dataloader.py", line 1346, in _next_data
    return self._process_data(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\venvs\AI\Lib\site-packages\torch\utils\data\dataloader.py", line 1372, in _process_data
    data.reraise()
  File "D:\venvs\AI\Lib\site-packages\torch\_utils.py", line 722, in reraise
    raise exception
AttributeError: Caught AttributeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "D:\venvs\AI\Lib\site-packages\torch\utils\data\_utils\worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\venvs\AI\Lib\site-packages\torch\utils\data\_utils\fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\venvs\AI\Lib\site-packages\torch\utils\data\_utils\fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
            ~~~~~~~~~~~~^^^^^
  File "D:\PycharmProjects\traiNNer\codes\data\aligned_dataset.py", line 126, in __getitem__
    A_transform = get_transform(
                  ^^^^^^^^^^^^^^
  File "D:\PycharmProjects\traiNNer\codes\dataops\augmentations.py", line 573, in get_transform
    transform_list.append(transforms.Resize(osize, method))
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PycharmProjects\traiNNer\codes\dataops\augmennt\augmennt\transforms.py", line 175, in __init__
    elif isinstance(size, collections.Iterable) and len(size) == 2:
                          ^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'collections' has no attribute 'Iterable'

**Comment by v0vanch0** [comment]
Have python 3.11
